apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-quickstart
spec:
  version: 8.15.0
  nodeSets:
  - name: ingest
    count: 1
    config:
      node.roles: ["master", "ingest"]  # Master-eligible + ingest
    volumeClaimTemplates: []  # No persistent storage needed for ingest
  - name: data
    count: 1
    config:
      node.roles: ["master", "data"]  # Master-eligible + data
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 19Gi