apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: elastic-system  # Must match ES and Kibana namespace
spec:
  version: 8.15.1  # EXACT match with your ES/Kibana version
  kibanaRef:
    name: kb-quickstart
  elasticsearchRefs:
    - name: es-quickstart
  mode: fleet
  fleetServerEnabled: true
  deployment:
    replicas: 1
    podTemplate:
      spec:
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0  # Required for many integrations
          
