name: Deploy ELK with ECK

on:
  push:
    branches: [ main ]
    paths:
      - 'k8s/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_TOKEN }}

    - name: Save kubeconfig
      run: doctl kubernetes cluster kubeconfig save <your-cluster-name-or-id>

    - name: Deploy Elasticsearch and Kibana
      run: |
        kubectl apply -f k8s/elasticsearch.yaml
        kubectl apply -f k8s/kibana.yaml

    - name: Wait for Elasticsearch ready
      run: kubectl wait --for=condition=Ready elasticsearch/es-quickstart --timeout=10m

    - name: Wait for Kibana ready
      run: kubectl wait --for=condition=Ready kibana/kb-quickstart --timeout=5m